--- #YAML:1.0
name:                Helios-Panoptes
version:             1.432
abstract:            Web administration interface to the Helios distributed job processing system
license:             perl
author:              
    - Andrew Johnson <lajandy at cpan dot org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    CGI::Application:              4.06
    CGI::Application::Plugin::DBH: 4
    DBD::Mock:                     0.11
    Helios:                        2
    HTML::Template:                2.9
    HTML::Template::Expr:          0.04
    Parse::RecDescent:             
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
